version: "3.8"
services:
  employee:
    image: aurelius0523/employee-service
    restart: always
    ports:
      - 9080:8080
    environment:
      SPRING_PROFILES_ACTIVE: compose

  inventory:
    image: aurelius0523/inventory-service
    restart: always
    ports:
      - 9081:8081
    environment:
      SPRING_PROFILES_ACTIVE: compose

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    # initialization script for postgres
    volumes:
      - ./postgresql-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 4432:5432

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411