server:
    port: 8081
spring:
    application:
        name: inventory-service
    datasource:
        password: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    zipkin:
        base-url: http://localhost:9411